### ISSUE TITLE
[repl.it] ImportError: Library ‘GL’ not found.

### ISSUE THREAD

**Issue by sasdallas** [pythonarcade/arcade#1093] opened 2022-02-17 14:53 UTC
## Bug Report
I cannot run the first tutorial code in repl.it.

### Actual behavior:
`ImportError: Library ‘GL’ not found.`
### Expected behavior:
A window to open.
### Steps to reproduce/example code:
Step 1: Put in the tutorial code for opening a window
Step 2: Run

**Comment by einarf** [comment] 2022-02-17 21:20
Must be something that repl.it changed. Maybe you need a subscription now for that to work?

**Comment by sasdallas** [comment] 2022-02-18 15:24
@einarf Yes, replit DID change something. I do have a subscription, it isn’t that. Repl switched from `install-pkg` to Nix. From and old issue, I found [this](https://replit.com/@EinarForselv/arcade-test#main.py) repl, which still uses the old system. Is there anyway to install OpenGL via nix?

**Comment by Cleptomania** [comment] 2022-02-19 06:44
Yeah the changes to nix have definitely broken things. I did a bit of investigation to this and will see if I can come up with something in the future, this is really a Pyglet problem but I'm not sure there's really much of a solution to it from the Pyglet side of the house without some real ugly specific patch that catches a repl.it instance hardcoded.

The core of the problem is that Pyglet uses ctypes to interact with system libraries like OpenGL, X11, etc. The methods by which Pyglet is able to search for these libraries is fundamentally incompatible with nix, and so it's not that the libraries don't exist, it's that Pyglet is incapable of finding them.

I've found [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/pyglet/default.nix) Nix package which proposes a solution by replacing the load_library function in Pyglet. As ugly as this is a derivation of this could probably be made to work with repl.it, however there is some question of if installing Pyglet via a nix package and then arcade via poetry or whatever will work together, as I'm guessing there's no way to install Pyglet via a nix package into the virtual environment that gets used by Poetry, so you'd probably have to manage all python packages through nix somehow.

I'll do some more digging with it a bit later.

I've verified that with previous repls I had, they're unaffected, and this does appear to be 100% related to the switch to Nix

**Comment by sasdallas** [comment] 2022-02-19 21:09
@Cleptomania agreed, no idea that Nix package even existed, thanks for the information! you can still use the `install-pkg` by either forking a repl before Nix, or I think you may be able to do it by using `C++ (Legacy)`?(not tried yet)

Also, previous repls aren't unaffected. I pulled an old python one up, changed the code, and it errored out with `OpenGL not found`.

**Comment by beef623** [comment] 2022-06-17 16:09
I'm running into this when I try to run an Arcade project from Termux also. Pygame stuff works fine, but I can't get anything using Arcade to run.

**Comment by einarf** [comment] 2022-06-17 18:07
> I'm running into this when I try to run an Arcade project from Termux also. Pygame stuff works fine, but I can't get anything using Arcade to run.

You probably need to install opengl for that to work. It would not work out of the box with a gpu based library like arcade or pyglet.

**Comment by einarf** [comment] 2022-12-03 05:01
Closing this for now.

**Closed as completed by einarf** 2022-12-03 05:01 UTC
