### ISSUE TITLE
TypeError: add_sprite() got an unexpected keyword argument 'moment'

### ISSUE THREAD

**Issue by alderven** [pythonarcade/arcade#976] opened 2021-09-30 06:00 UTC
Run code from tutorial:
https://api.arcade.academy/en/latest/tutorials/pymunk_platformer/pymunk_demo_platformer_12.html#pymunk-demo-platformer-12

Get error here:
```
self.physics_engine.add_sprite(self.player_sprite,
                               friction=PLAYER_FRICTION,
                               mass=PLAYER_MASS,
                               moment=arcade.PymunkPhysicsEngine.MOMENT_INF,
                               collision_type="player",
                               max_horizontal_velocity=PLAYER_MAX_HORIZONTAL_SPEED,
                               max_vertical_velocity=PLAYER_MAX_VERTICAL_SPEED)
```
Error message:
```
Traceback (most recent call last):
  File "C:/pymunk_demo_platformer_12/doc/tutorials/pymunk_platformer/pymunk_demo_platformer_12.py", line 524, in <module>
    main()
  File "C:/pymunk_demo_platformer_12/doc/tutorials/pymunk_platformer/pymunk_demo_platformer_12.py", line 519, in main
    window.setup()
  File "C:/pymunk_demo_platformer_12/doc/tutorials/pymunk_platformer/pymunk_demo_platformer_12.py", line 317, in setup
    self.physics_engine.add_sprite(self.player_sprite,
TypeError: add_sprite() got an unexpected keyword argument 'moment'
```

**Comment by pushfoo** [comment] 2021-09-30 06:22
1. Try `moment_of_inertia` as the argument name instead of `moment`
2. What version of arcade are you on?

**Comment by alderven** [comment] 2021-09-30 06:28
> Try `moment_of_inertia` as the argument name instead of `moment`

It works. Thanks!

> What version of arcade are you on?

`2.6.3`

**Comment by pushfoo** [comment] 2021-09-30 06:43
As noted in #977 , this was caused by an earlier commit that updated type annotations, but also renamed the argument to `PymunkPhysicsEngine.add_sprite` without updating the doc. That ticket should be addressed first so we can update the doc with the correct variable name.

**Comment by pushfoo** [comment] 2021-09-30 07:42
Duplicate of #932

**Comment by einarf** [comment] 2021-11-03 14:00
2.6.4 released

**Closed as completed by einarf** 2021-11-03 14:00 UTC
Labels: fix waiting for release
