### ISSUE TITLE
Bloom defender examples have broken offsets on development

### ISSUE THREAD

**Issue by pushfoo** [pythonarcade/arcade#1424] opened 2022-12-02 21:00 UTC
## System Info
```
$ python -m arcade

Arcade 2.7.1.dev8
-----------------
vendor: Intel
renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
version: (4, 6)
python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
platform: linux
```
```
$ hostnamectl
 ...
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-19-amd64
      Architecture: x86-64
```
### Actual behavior:
![image](https://user-images.githubusercontent.com/36696816/205384260-7c3ffee8-e467-44ce-94ad-4db5a68305e5.png)

### Expected behavior:
![image](https://user-images.githubusercontent.com/36696816/205384455-d4b23732-1e95-4b11-83ef-c567f38842cf.png)

### Steps to reproduce/example code:
Run either of the following examples on the OS / hardware version listed above:
1. [`arcade/examples/bloom_defender.py`](https://github.com/pythonarcade/arcade/blob/development/arcade/examples/bloom_defender.py)
2. [`arcade/experimental/bloom_multilayer_defender.py`](https://github.com/pythonarcade/arcade/blob/development/arcade/experimental/bloom_multilayer_defender.py)

**Comment by pushfoo** [comment] 2022-12-02 21:11
This happens regardless of whether the color constant in #1425 is used.

**Comment by pushfoo** [comment] 2022-12-03 01:01
Per discord discussion, this has been broken for a while, and it's not clear when it broke.

**Comment by einarf** [comment] 2022-12-03 01:04
Duplicate of #946

**Closed as completed by einarf** 2022-12-03 01:04 UTC
