### ISSUE TITLE
Cannot use multiple textures as channels in fragment shader

### ISSUE THREAD

**Issue by user2332533** [pythonarcade/arcade#1453] opened 2023-01-10 19:31 UTC
## Bug Report

`texture0.use(0)` seems to bind to all channels in fragment shader and `texture1.use(1)` does not bind to any. 

## System Info

```
Arcade 2.6.17
-------------
vendor: Intel
renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
version: (4, 6)
python: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
platform: linux
```

### Actual behavior:
With 
```
# Python code
texture0.use(0)
texture1.use(1)
...
# Fragment shader
#version 330
uniform sampler2D t0;
uniform sampler2D t1;
```
both `t0` and `t1` refer to `texture0`.
 
### Expected behavior:

I would expect `t0` to refer to `texture0` and `t1` to refer to `texture1`.

### Steps to reproduce/example code:

This is a pretty minimal example where the shader blends `tex_0` with `tex_0` to create a solid color rather than blending `tex_0` with `tex_1` to create a gradient.

```python
import arcade


class MyWindow(arcade.Window):

  def __init__(self):
    global cs, vs, gs, fs
    super().__init__(80, 80, "X")
    self.center_window()

    # Create textures and FBOs
    self.tex_0 = self.ctx.texture((self.width, self.height))
    self.fbo_0 = self.ctx.framebuffer(color_attachments=[self.tex_0])

    self.tex_1 = self.ctx.texture((self.width, self.height))
    self.fbo_1 = self.ctx.framebuffer(color_attachments=[self.tex_1])
    
    self.quad_fs = arcade.gl.geometry.quad_2d_fs()

    # Create shader program
    self.prog = self.ctx.program(
      vertex_shader="""#version 330
      in vec2 in_vert;
      in vec2 in_uv;
      out vec2 uv;
      void main()
      {
        gl_Position = vec4(in_vert, 0., 1.);
        uv = in_uv;
      }""",
      fragment_shader="""#version 330
      uniform sampler2D t0;
      uniform sampler2D t1;
      in vec2 uv;
      out vec4 fragColor;
      void main()
      {
        // Expect same output as 
        // fragColor = mix(vec4(0.0, 0.0, 1.0, 1.0), vec4(1.0,0.0,0.0,1.0), smoothstep(0.0, 1.0, uv.x));
        fragColor = mix(texture(t0, uv), texture(t1, uv), smoothstep(0.0, 1.0, uv.x));
      }"""
    )

  def on_draw(self):
    self.clear()

    # Fill the textures with solid colours
    self.fbo_0.clear(color=(0.0, 0.0, 1.0, 1.0), normalized=True)
    self.fbo_1.clear(color=(1.0, 0.0, 0.0, 1.0), normalized=True)

    # Bind our textures to channels
    self.tex_0.use(0)
    self.tex_1.use(1)

    # Run the shader and render
    self.quad_fs.render(self.prog)


app = MyWindow()
arcade.run()
```
Actual output:
![acual](https://user-images.githubusercontent.com/95532390/211646397-5d2e8a28-9af5-460c-aedf-3c5b06e81621.png)

Expected output:
![expected](https://user-images.githubusercontent.com/95532390/211646527-f4695be9-0a25-48c8-af68-76c363423831.png)

**Comment by einarf** [comment] 2023-01-11 08:30
Weird. I will take a look at this asap.

**Comment by einarf** [comment] 2023-01-11 09:20
The problem is that you have to configure what texture channel each sampler should read from. Right now both samplers are reding from channel 0 since this is default. Sampler uniforms are just normal integer uniforms you can set.

Right after program creation you can do the following:
```py
    self.prog["t0"] = 0
    self.prog["t1"] = 1
```

You can also use layout qualifiers in the shader itself, but this will bump the GL requirements from 3.3 to 4.2, meaning you should pass `gl_version=(4, 2)` to the window on creation.

```glsl
layout(binding=0) uniform sampler2D t0;
layout(binding=1) uniform sampler2D t1;
```

https://www.khronos.org/opengl/wiki/Sampler_(GLSL)#Version_4.20_binding

**Comment by einarf** [comment] 2023-01-11 09:29
Closing this for now. Be free to comment or reopen if anything else related to this is lingering.

We also have an `arcade-gl` channel on the arcade discord server: https://discord.gg/ZjGDqMp

**Closed as completed** 2023-01-11 09:29 UTC

**Comment by einarf** [comment] 2023-01-11 09:32
Also just to explain how texture binding works in GL.

We have 8 (minimum) or more texture channels:

```
Channel 0
Channel 1
Channel 2
...
```

These are like low level hardware registers of the GPU. How many you have depends on the hardware.

The samplers in shaders are configured with an integer value what register/texture unit they are supposed to read from.
As described above this is done in two ways:
* Set the uniform value directly specifying the channel
* Use layout qualifiers in the shader

This is also how uniform buffer objects, shader storage buffers and image units works.

**Comment by user2332533** [comment] 2023-01-11 13:32
Many thanks. This is extremely useful. And apologies for mistaking my lack of understanding for a bug. 

I've added some examples to a docs tutorial PR #1455 so hopefully other people won't make my mistake.

One tangential question:
Is it possible to access the texture in the default frambuffer? `ctx.fbo.color_attachments` is an empty list so it doesn't follow the pattern in `RenderTargetTexture`.

**Comment by einarf** [comment] 2023-01-11 14:55
> I've added some examples to a docs tutorial PR #1455 so hopefully other people won't make my mistake.

Thanks! Might just merge this and move it later. We were planning to make some GL tutorial, but the lack of time have prevented it so far.

> Is it possible to access the texture in the default frambuffer? `ctx.fbo.color_attachments` is an empty list so it doesn't follow the pattern in `RenderTargetTexture`

It's not possible to read the color attachment from the default framebuffer in a sampler, no. Most games today don't do any rendering to the default framebuffer anyway. It's all offscreen and then rendered to the screen with a fullscreen quad and texture shader as last step. This step also give the opportunity to do simple post processing.
