### ISSUE TITLE
Add support for bitmapped fonts

### ISSUE THREAD

**Issue by gran4** [pythonarcade/arcade#1685] opened 2023-04-05 21:11 UTC
### What should be added/changed?
Add something for custom text.

### What would it help with?
It would make it easier to put custom fonts(not actually fonts, but pictures) into a game.

**Comment by pushfoo** [comment] 2023-04-05 21:27
> custom fonts(not actually fonts, but pictures)

Do you mean bitmap fonts from sprite sheets like this one?
![image](https://user-images.githubusercontent.com/36696816/230213378-8e577891-f032-40b4-825c-e1de7ae3394c.png)

I've brought it up in the past in #842, but closed it since [full bitmap support should probably be added to pyglet first](https://github.com/pythonarcade/arcade/issues/842#issuecomment-1454367176). That may be somewhat difficult and will require work on the arcade side as well. If you need something sooner, you may be able to put something together yourself with the UI classes.

**Comment by gran4** [comment] 2023-04-06 03:42
That's what I mean, just didn't know the name. The thing I created doesn't split the bit map for you. I can add that in a separate function

**Comment by pushfoo** [comment] 2023-04-07 02:11
As I outlined in [this PR discussion comment](https://github.com/pythonarcade/arcade/pull/1686#discussion_r1160374063):

1. General font rendering is very hard to solve
2. The reliable but difficult way to handle this is probably adding bitmap font support to pyglet, then arcade
3. This issue's intended use cases are unclear

For anyone looking for a fast development solution, here's a table of goals and ways to achieve them:

| Goal                                                     | Alternative to implementing custom text renderer                    |
|----------------------------------------------------------|--------------------------------------------------------------|
| Use a pixel font | Use [the built-in kenney fonts](https://api.arcade.academy/en/latest/examples/drawing_text_objects.html) or make a custom TTF font with a tool like [BitFontMaker2](https://www.pentacom.jp/pentacom/bitfontmaker2/) & load it                          |
| Embed custom images inline with text                     | Use pyglet's HTML labels & [their support for custom inline elements](https://pyglet.readthedocs.io/en/latest/programming_guide/text.html#custom-elements) |
| Arrange GUI icons in a line                                  | [Use UITextureButton with layouts](https://api.arcade.academy/en/latest/examples/gui_widgets.html#gui-widgets)                                        |

**Comment by DigiDuncan** [comment] 2023-04-09 00:22
This has come up so many times, that I really think we either need to
a) straight up add rudimentary bitmap text support to Arcade (maybe restrict it to monospace?)
b) get Pyglet to do it
c) have a page detailing why were *aren't* doing this, and maybe even "how to implement it yourself."

Pixel fonts have a lot of issues (which I can get into if required) and Pyglet's HTML labels are very lacking in a lot of ways.

**Comment by pushfoo** [comment] 2023-04-11 16:02
> b) get Pyglet to do it

To my understanding, this may be the best & least brittle approach, even if it might require the most work. Anything we implement will be duplicating the extensive work already done by pyglet's text rendering.

I've started digging into the pyglet text stack again recently (https://github.com/pyglet/pyglet/pull/806). There may be multiple font rendering backends from what I read in the source and was told on Discord, so it may be more complicated than just loading bitmap data into a glyph atlas.

> c) have a page detailing why were aren't doing this, and maybe even "how to implement it yourself."

[My comment above](https://github.com/pythonarcade/arcade/issues/1685#issuecomment-1499855850) is intended to be the start of a page like that. #1691 would be model I'd follow for a dedicated section of the Programming Guide. It should also cover things like rendering frequently used text to sprites.

**Comment by gran4** [comment] 2023-04-15 23:13
> This has come up so many times, that I really think we either need to a) straight up add rudimentary bitmap text support to Arcade (maybe restrict it to monospace?) b) get Pyglet to do it c) have a page detailing why were _aren't_ doing this, and maybe even "how to implement it yourself."
> 
> Pixel fonts have a lot of issues (which I can get into if required) and Pyglet's HTML labels are very lacking in a lot of ways.

Maybe we could put an example?

**Comment by pvcraven** [comment] 2023-05-06 22:02
This is a duplicate of [Issue 433](https://github.com/pythonarcade/arcade/issues/433). If someone is wanting to work on this, please reopen to track. Otherwise I'm going to close to reduce clutter in our issue list.

**Closed as completed by pvcraven** 2023-05-06 22:02 UTC
Labels: duplicate, enhancement
