### ISSUE TITLE
Background music should stop when the window closes, but doesn't

### ISSUE THREAD

**Issue by Millwr1ght** [pythonarcade/arcade#912] opened 2021-07-08 05:49 UTC
## Bug Report
When the arcade window is closed while playing background music, music continues to play.

### Actual behavior:
Background music doesn't stop.
 
### Expected behavior:
Background music should stop when the window closes.

### Steps to reproduce/example code:
OS: Windows 10
Errors specifically occurred while using the thonny IDE

**Comment by Cleptomania** [comment] 2021-07-10 18:02
Is this with the exact code from the background music example?

I'm unable to reproduce this on Linux or Windows, with either the current dev version of Arcade of 2.5.7

Could you try and run it without Thonny directly via the command line and see if you have the same result? It could be that Thonny is keeping the process alive after the Window closes somehow.

Audio is currently played using the same main thread as the application so there isn't any multi-threading going on that would be not being handled on window close.

**Comment by Millwr1ght** [comment] 2021-07-13 01:02
Running the program outside of thonny resulted in the music stopping as it should. Seems to be a problem with thonny.

**Comment by Cleptomania** [comment] 2021-07-13 01:34
Alright I’m going to close this then as there’s not really anything we can do about it. Thonny’s debugger is somehow just keeping the process alive. You may be able to configure it to not do that, but I’m not sure.

**Closed as completed by Cleptomania** 2021-07-13 01:34 UTC

**Comment by einarf** [comment] 2021-07-13 05:13
You can activcely stop the music on appliation exit?
