### ISSUE TITLE
Update Pymunk platformer tutorial for 2.6

### ISSUE THREAD

**Issue by Cleptomania** [pythonarcade/arcade#932] opened 2021-08-31 14:10 UTC
The Pymunk platformer tutorial still needs updated for 2.6. I believe some pieces of the code have been updated, but I don’t think the whole thing has. I know at the least the line highlighting in the tutorial is broke. Because of re-writing some pieces of the code.

**Comment by pushfoo** [comment] 2021-09-30 07:34
#976 is a duplicate of this ticket, and #979 is a prerequisite for this to be closed,

**Comment by einarf** [comment] 2022-04-03 01:25
I would think this one should be closed?

**Closed as completed** 2022-04-22 20:13 UTC
Labels: documentation, examples
