### ISSUE TITLE
Supporting for setting pitch of sounds

### ISSUE THREAD

**Issue by Cleptomania** [pythonarcade/arcade#1198] opened 2022-04-25 18:58 UTC
Pyglet has support for setting the pitch of a sound by adjust the `pitch` attribute of a Player object. We can easily add this support to Arcade by adding a pitch argument to `arcade.sound.play()` with a default of 1.0 and passing it through to the player.

**Comment by iansedano** [comment] 2022-04-30 20:50
I'll try this one

**Comment by Cleptomania** [comment] 2022-04-30 22:21
This has been implemented with #1208

**Comment by pushfoo** [comment] 2022-05-02 22:29
I don't quite understand how it works, so beginners will probably be confused as well. Maybe we could clarify the documentation and add a tiny piano example that bends the pitch of a single sample to cover 1 octave?

**Comment by pushfoo** [comment] 2022-05-03 07:09
The [pyglet doc](https://pyglet.readthedocs.io/en/latest/modules/media.html#pyglet.media.player.Player.pitch) makes the underlying behavior much clearer:
> The pitch shift to apply to the sound.
>
>The nominal pitch is 1.0. A pitch of 2.0 will sound one octave higher, and play twice as fast. A pitch of 0.5 will sound one octave lower, and play twice as slow. A pitch of 0.0 is not permitted.

Something like `play_speed` might be clearer for our users, even if it isn't a 1:1 match to pyglet's argument name.

**Comment by iansedano** [comment] 2022-05-03 18:43
I agree that `pitch` is not such an intuitive attribute. As a beginner, you might expect the pitch to be shifted but the length to remain the same. Likewise, if you change the speed, you might assume that the pitch would stay the same.

So, perhaps we could implement some additional methods to preserve pitch when changing speed and preserving speed (or length) when changing pitch. That also has the additional advantage of keeping the same argument names, just adding a bit of user-facing functionality to pyglet.

If we did this, then we might have an additional argument to bypass this "corrective" default behavior. In the case of `pitch` it could be `compensate_speed=True`, for instance.

However, looking over the pyglet docs, I can't immediately see an obvious way to achieve this. I'll look into it a bit further, but I think `play_speed` is a good term for what is happening for now. The pitch shifting behavior can be clarified in the docs.

**Comment by pushfoo** [comment] 2022-05-03 20:01
Although a a few audio tools tools implement pitch shifting while preserving playback speed, it's lossy and can sound very strange. I think we might want to do the following:

1. rename the argument to one of the following before a release gets cut:`play_speed`, `playback_speed`, or `speed`
2. put off further changes to the playback until we understand the problem better
3. leave this issue open

One thing we could do is add some sound processing capabilities that can save processed audio as new sound object instances. We might be headed in that direction with textures.

**Comment by pushfoo** [comment] 2022-05-04 04:21
I'm working on a playable piano synth as an advanced example. If anyone wants to beat me to it, they could do an additional simpler example that changes pitches on a single sound. Ideas I've had include:
* A charged attack as described in the dupe of this issue (#1199)
* Randomized pitch shift for hit sounds

**Comment by pushfoo** [comment] 2022-05-04 06:55
@iansedano I apologize for missing the example changes in df1e6ae69. The idea is good, but I think it might be better if placed in a new example which is:
 1. Titled appropriately & placed under the [Sound section on the examples page](https://api.arcade.academy/en/latest/examples/index.html#sound)
 2. Small & focused on showcasing randomized pitch
 
 This would have the following advantages:
 1. Easier for beginners to find
 2. Easier for beginners to read and understand
 
 Would you be up for trying to add a new example?

**Comment by iansedano** [comment] 2022-05-07 19:07
@pushfoo no worries for missing the change in https://github.com/pythonarcade/arcade/commit/df1e6ae69bc81a361582515cdc574082a5298aa2, it was very small! I gave the new example a shot, and renamed the parameter from `pitch` to `speed` - see PR https://github.com/pythonarcade/arcade/pull/1216

What do you think? If that is all good, then I'll adjust the docs.

**Closed as completed** 2022-05-16 23:36 UTC
Labels: enhancement, fix waiting for release, good first issue
