### ISSUE TITLE
TopLeft coordinates when  drawing rectangles

### ISSUE THREAD

**Issue by pyweeker** [pythonarcade/arcade#996] opened 2021-10-07 08:08 UTC
Hello,
it is not always handy to draw from x,y centers .
Is it possible to get 4 angles or only topleft from calling arcade.draw_rectangle_filled for example ?

**Comment by einarf** [comment] 2021-10-07 08:17
There are version using xywh : https://api.arcade.academy/en/latest/api/drawing_primitives.html

**Comment by pyweeker** [comment] 2021-10-08 12:14
thank you Einar

Le jeu. 7 oct. 2021 à 10:18, Einar Forselv ***@***.***> a
écrit :

**Comment by einarf** [comment] 2021-10-08 15:29
Closing this. Be free to reopen if the issue is not resolved.

**Closed as completed by einarf** 2021-10-08 15:29 UTC
Labels: question
